---
http_interactions:
- request:
    method: post
    uri: https://FILTERED_USERNAME:FILTERED_PASSWORD@amsprd0710.outlook.com/EWS/Exchange.asmx
    body:
      encoding: UTF-8
      string: |
        <?xml version="1.0"?>
        <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
          <soap:Body>
            <GetUserConfiguration xmlns="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
              <UserConfigurationName Name="CategoryList">
                <t:FolderId Id="AQAhAGNoYWRfZXhjaGFuZ2VydGVzdGluZ0BvdXRsb28Aay5jb20ALgAABKlVK7wi0Um5a7NdGSAWsQEATutsxsDoLkiasjWoT1GLIQAAAgENAAAA"/>
              </UserConfigurationName>
              <UserConfigurationProperties>All</UserConfigurationProperties>
            </GetUserConfiguration>
          </soap:Body>
        </soap:Envelope>
    headers:
      Soapaction:
      - http://schemas.microsoft.com/exchange/services/2006/messages/GetUserConfiguration
      Content-Type:
      - text/xml; charset=utf-8
      Authorization:
      - Basic Y2hhZF9leGNoYW5nZXJ0ZXN0aW5nQG91dGxvb2suY29tOmV4Y2hhbmdlcl9zcGVjMzMzIQ==
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - private
      Transfer-Encoding:
      - chunked
      Content-Type:
      - text/xml; charset=utf-8
      Server:
      - Microsoft-IIS/8.0
      Request-Id:
      - 5dcb0335-4b89-4646-9a57-598fb46f2ddc
      X-Calculatedbetarget:
      - CO2PR0801MB552.namprd08.prod.outlook.com
      X-Backendhttpstatus:
      - '200'
      Set-Cookie:
      - exchangecookie=ec278a41bde94e548600e1d20835b379; expires=Fri, 11-Aug-2017
        13:11:14 GMT; path=/; HttpOnly
      X-Ewshandler:
      - GetUserConfiguration
      X-Aspnet-Version:
      - 4.0.30319
      X-Diaginfo:
      - CO2PR0801MB552
      X-Beserver:
      - CO2PR0801MB552
      X-Powered-By:
      - ASP.NET
      X-Feserver:
      - CY1PR21CA0094
      Date:
      - Thu, 11 Aug 2016 13:11:13 GMT
    body:
      encoding: UTF-8
      string: <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo
        MajorVersion="15" MinorVersion="1" MajorBuildNumber="549" MinorBuildNumber="25"
        xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/></s:Header><s:Body><m:GetUserConfigurationResponse
        xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:GetUserConfigurationResponseMessage
        ResponseClass="Success"><m:ResponseCode>NoError</m:ResponseCode><m:UserConfiguration><t:UserConfigurationName
        Name="CategoryList"><t:FolderId Id="AQAhAGNoYWRfZXhjaGFuZ2VydGVzdGluZ0BvdXRsb28Aay5jb20ALgAABKlVK7wi0Um5a7NdGSAWsQEATutsxsDoLkiasjWoT1GLIQAAAgENAAAA"/></t:UserConfigurationName><t:ItemId
        Id="AQAhAGNoYWRfZXhjaGFuZ2VydGVzdGluZ0BvdXRsb28Aay5jb20ARgAABKlVK7wi0Um5a7NdGSAWsQcATutsxsDoLkiasjWoT1GLIQAAAgENAAAATutsxsDoLkiasjWoT1GLIQAAAhjZAAAA"
        ChangeKey="CQAAABYAAABO62zGwOguSJqyNahPUYshAAA8qRMK"/><t:XmlData>77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48Y2F0ZWdvcmllcyBsYXN0U2F2ZWRUaW1lPSIyMDE2LTA4LTEwVDE2OjQwOjUxLjU5MzMyNjhaIiB4bWxucz0iQ2F0ZWdvcnlMaXN0LnhzZCI+PGNhdGVnb3J5IHJlbmFtZU9uRmlyc3RVc2U9IjEiIG5hbWU9IlJlZCBjYXRlZ29yeSIgY29sb3I9IjAiIGtleWJvYXJkU2hvcnRjdXQ9IjAiIGxhc3RUaW1lVXNlZE5vdGVzPSIyMDE2LTA1LTA2VDE1OjUwOjA4LjY5MzgyNjZaIiBsYXN0VGltZVVzZWRKb3VybmFsPSIyMDE2LTA1LTA2VDE1OjUwOjA4LjY5MzgyNjZaIiBsYXN0VGltZVVzZWRDb250YWN0cz0iMjAxNi0wNS0wNlQxNTo1MDowOC42OTM4MjY2WiIgbGFzdFRpbWVVc2VkVGFza3M9IjIwMTYtMDUtMDZUMTU6NTA6MDguNjkzODI2NloiIGxhc3RUaW1lVXNlZENhbGVuZGFyPSIyMDE2LTA1LTA2VDE1OjUwOjA4LjY5MzgyNjZaIiBsYXN0VGltZVVzZWRNYWlsPSIyMDE2LTA1LTA2VDE1OjUwOjA4LjY5MzgyNjZaIiBsYXN0VGltZVVzZWQ9IjIwMTYtMDUtMDZUMTU6NTA6MDguNjkzODI2NloiIGd1aWQ9IntiY2E2Y2JjOC03NjgzLTRlNDktOWU2NC1iNmQxNjAwNTk0OTh9IiAvPjxjYXRlZ29yeSByZW5hbWVPbkZpcnN0VXNlPSIxIiBuYW1lPSJPcmFuZ2UgY2F0ZWdvcnkiIGNvbG9yPSIxIiBrZXlib2FyZFNob3J0Y3V0PSIwIiBsYXN0VGltZVVzZWROb3Rlcz0iMjAxNi0wNS0wNlQxNTo1MDowOC42OTM4MjY2WiIgbGFzdFRpbWVVc2VkSm91cm5hbD0iMjAxNi0wNS0wNlQxNTo1MDowOC42OTM4MjY2WiIgbGFzdFRpbWVVc2VkQ29udGFjdHM9IjIwMTYtMDUtMDZUMTU6NTA6MDguNjkzODI2NloiIGxhc3RUaW1lVXNlZFRhc2tzPSIyMDE2LTA1LTA2VDE1OjUwOjA4LjY5MzgyNjZaIiBsYXN0VGltZVVzZWRDYWxlbmRhcj0iMjAxNi0wNS0wNlQxNTo1MDowOC42OTM4MjY2WiIgbGFzdFRpbWVVc2VkTWFpbD0iMjAxNi0wNS0wNlQxNTo1MDowOC42OTM4MjY2WiIgbGFzdFRpbWVVc2VkPSIyMDE2LTA1LTA2VDE1OjUwOjA4LjY5MzgyNjZaIiBndWlkPSJ7Yzc1NzNkODYtNzU1Ny00ZmNmLWJkZmMtZWJiMzZhMmE4ZmM2fSIgLz48Y2F0ZWdvcnkgcmVuYW1lT25GaXJzdFVzZT0iMSIgbmFtZT0iWWVsbG93IGNhdGVnb3J5IiBjb2xvcj0iMyIga2V5Ym9hcmRTaG9ydGN1dD0iMCIgbGFzdFRpbWVVc2VkTm90ZXM9IjIwMTYtMDUtMDZUMTU6NTA6MDguNjkzODI2NloiIGxhc3RUaW1lVXNlZEpvdXJuYWw9IjIwMTYtMDUtMDZUMTU6NTA6MDguNjkzODI2NloiIGxhc3RUaW1lVXNlZENvbnRhY3RzPSIyMDE2LTA1LTA2VDE1OjUwOjA4LjY5MzgyNjZaIiBsYXN0VGltZVVzZWRUYXNrcz0iMjAxNi0wNS0wNlQxNTo1MDowOC42OTM4MjY2WiIgbGFzdFRpbWVVc2VkQ2FsZW5kYXI9IjIwMTYtMDUtMDZUMTU6NTA6MDguNjkzODI2NloiIGxhc3RUaW1lVXNlZE1haWw9IjIwMTYtMDUtMDZUMTU6NTA6MDguNjkzODI2NloiIGxhc3RUaW1lVXNlZD0iMjAxNi0wNS0wNlQxNTo1MDowOC42OTM4MjY2WiIgZ3VpZD0ie2YxNWI0N2RiLTc1NDEtNGQ5Mi04OGY1LWM3Njg4ZTM4NWQ3YX0iIC8+PGNhdGVnb3J5IHJlbmFtZU9uRmlyc3RVc2U9IjEiIG5hbWU9IkdyZWVuIGNhdGVnb3J5IiBjb2xvcj0iNCIga2V5Ym9hcmRTaG9ydGN1dD0iMCIgbGFzdFRpbWVVc2VkTm90ZXM9IjIwMTYtMDUtMDZUMTU6NTA6MDguNjkzODI2NloiIGxhc3RUaW1lVXNlZEpvdXJuYWw9IjIwMTYtMDUtMDZUMTU6NTA6MDguNjkzODI2NloiIGxhc3RUaW1lVXNlZENvbnRhY3RzPSIyMDE2LTA1LTA2VDE1OjUwOjA4LjY5MzgyNjZaIiBsYXN0VGltZVVzZWRUYXNrcz0iMjAxNi0wNS0wNlQxNTo1MDowOC42OTM4MjY2WiIgbGFzdFRpbWVVc2VkQ2FsZW5kYXI9IjIwMTYtMDUtMDZUMTU6NTA6MDguNjkzODI2NloiIGxhc3RUaW1lVXNlZE1haWw9IjIwMTYtMDUtMDZUMTU6NTA6MDguNjkzODI2NloiIGxhc3RUaW1lVXNlZD0iMjAxNi0wNS0wNlQxNTo1MDowOC42OTM4MjY2WiIgZ3VpZD0iezJmYmZiMjM5LTYyYTQtNDUxMi1hYzBhLWUxNGQ4MjU0NjIwNH0iIC8+PGNhdGVnb3J5IHJlbmFtZU9uRmlyc3RVc2U9IjEiIG5hbWU9IkJsdWUgY2F0ZWdvcnkiIGNvbG9yPSI3IiBrZXlib2FyZFNob3J0Y3V0PSIwIiBsYXN0VGltZVVzZWROb3Rlcz0iMjAxNi0wNS0wNlQxNTo1MDowOC42OTM4MjY2WiIgbGFzdFRpbWVVc2VkSm91cm5hbD0iMjAxNi0wNS0wNlQxNTo1MDowOC42OTM4MjY2WiIgbGFzdFRpbWVVc2VkQ29udGFjdHM9IjIwMTYtMDUtMDZUMTU6NTA6MDguNjkzODI2NloiIGxhc3RUaW1lVXNlZFRhc2tzPSIyMDE2LTA1LTA2VDE1OjUwOjA4LjY5MzgyNjZaIiBsYXN0VGltZVVzZWRDYWxlbmRhcj0iMjAxNi0wOC0xMFQxNjo0MDowMC45NTM1MzY5WiIgbGFzdFRpbWVVc2VkTWFpbD0iMjAxNi0wNS0wNlQxNTo1MDowOC42OTM4MjY2WiIgbGFzdFRpbWVVc2VkPSIyMDE2LTA4LTEwVDE2OjQwOjAwLjk1MzUzNjlaIiBndWlkPSJ7MTA1ZjE5ZmQtNWI1Ni00Yjk4LWEzMjEtOWRjYzFjOTA4ZWE0fSIgLz48Y2F0ZWdvcnkgcmVuYW1lT25GaXJzdFVzZT0iMSIgbmFtZT0iUHVycGxlIGNhdGVnb3J5IiBjb2xvcj0iOCIga2V5Ym9hcmRTaG9ydGN1dD0iMCIgbGFzdFRpbWVVc2VkTm90ZXM9IjIwMTYtMDUtMDZUMTU6NTA6MDguNjkzODI2NloiIGxhc3RUaW1lVXNlZEpvdXJuYWw9IjIwMTYtMDUtMDZUMTU6NTA6MDguNjkzODI2NloiIGxhc3RUaW1lVXNlZENvbnRhY3RzPSIyMDE2LTA1LTA2VDE1OjUwOjA4LjY5MzgyNjZaIiBsYXN0VGltZVVzZWRUYXNrcz0iMjAxNi0wNS0wNlQxNTo1MDowOC42OTM4MjY2WiIgbGFzdFRpbWVVc2VkQ2FsZW5kYXI9IjIwMTYtMDUtMDZUMTU6NTA6MDguNjkzODI2NloiIGxhc3RUaW1lVXNlZE1haWw9IjIwMTYtMDUtMDZUMTU6NTA6MDguNjkzODI2NloiIGxhc3RUaW1lVXNlZD0iMjAxNi0wNS0wNlQxNTo1MDowOC42OTM4MjY2WiIgZ3VpZD0ie2YwMDVkOTNmLWMxYTItNGY2ZS05ZTYyLWU1YmU5NThhMmY2ZH0iIC8+PGNhdGVnb3J5IHJlbmFtZU9uRmlyc3RVc2U9IjAiIG5hbWU9IlRlc3QgTm8gQ29sb3IgQ2F0IiBjb2xvcj0iLTEiIGtleWJvYXJkU2hvcnRjdXQ9IjAiIGxhc3RUaW1lVXNlZE5vdGVzPSIyMDE2LTA4LTEwVDE0OjA4OjQ1Ljg0MTEyNzFaIiBsYXN0VGltZVVzZWRKb3VybmFsPSIyMDE2LTA4LTEwVDE0OjA4OjQ1Ljg0MTEyNzFaIiBsYXN0VGltZVVzZWRDb250YWN0cz0iMjAxNi0wOC0xMFQxNDowODo0NS44NDExMjcxWiIgbGFzdFRpbWVVc2VkVGFza3M9IjIwMTYtMDgtMTBUMTQ6MDg6NDUuODQxMTI3MVoiIGxhc3RUaW1lVXNlZENhbGVuZGFyPSIyMDE2LTA4LTEwVDE2OjQwOjAwLjk1MzUzNjlaIiBsYXN0VGltZVVzZWRNYWlsPSIyMDE2LTA4LTEwVDE0OjA4OjQ1Ljg0MTEyNzFaIiBsYXN0VGltZVVzZWQ9IjIwMTYtMDgtMTBUMTY6NDA6MDAuOTUzNTM2OVoiIGd1aWQ9Ins3OTZlMGJjMy0zYzA5LTRmMzYtOTUyZS05MDllZWE4ODI1YWV9IiAvPjxjYXRlZ29yeSByZW5hbWVPbkZpcnN0VXNlPSIwIiBuYW1lPSJUZXN0IFBlYWNoIENhdGVnb3J5IiBjb2xvcj0iMiIga2V5Ym9hcmRTaG9ydGN1dD0iMCIgbGFzdFRpbWVVc2VkTm90ZXM9IjIwMTYtMDgtMTBUMTY6NDA6NTEuNTkxMzI1MloiIGxhc3RUaW1lVXNlZEpvdXJuYWw9IjIwMTYtMDgtMTBUMTY6NDA6NTEuNTkxMzI1MloiIGxhc3RUaW1lVXNlZENvbnRhY3RzPSIyMDE2LTA4LTEwVDE2OjQwOjUxLjU5MTMyNTJaIiBsYXN0VGltZVVzZWRUYXNrcz0iMjAxNi0wOC0xMFQxNjo0MDo1MS41OTEzMjUyWiIgbGFzdFRpbWVVc2VkQ2FsZW5kYXI9IjIwMTYtMDgtMTBUMTY6NDA6NTEuNTkxMzI1MloiIGxhc3RUaW1lVXNlZE1haWw9IjIwMTYtMDgtMTBUMTY6NDA6NTEuNTkxMzI1MloiIGxhc3RUaW1lVXNlZD0iMjAxNi0wOC0xMFQxNjo0MDo1MS41OTEzMjUyWiIgZ3VpZD0iezYxOWU4ZGZiLTg0ZmYtNGE0NS1hZWRlLWVjODYwM2FiM2UwOH0iIC8+PC9jYXRlZ29yaWVzPg==</t:XmlData></m:UserConfiguration></m:GetUserConfigurationResponseMessage></m:ResponseMessages></m:GetUserConfigurationResponse></s:Body></s:Envelope>
    http_version: 
  recorded_at: Thu, 11 Aug 2016 13:11:15 GMT
recorded_with: VCR 3.0.1
